import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { getRemoteReport, renewPatientSession, type PatientReport } from "@/lib/patient-api";
import { useMediCare } from "@/lib/medicare-store";

export default function ReportDetailScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { session } = useMediCare(); const [report, setReport] = useState<PatientReport | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const load = async () => { const visitId = Number(id); if (!session || !Number.isInteger(visitId)) { setError("سجّل الدخول لعرض التقرير المرتبط بالزيارة."); setLoading(false); return; } try { setReport(await getRemoteReport(await renewPatientSession(session), visitId)); } catch (reason) { setError(reason instanceof Error ? reason.message : "المخرج غير متاح لهذه الزيارة."); } finally { setLoading(false); } }; void load(); }, [id, session]);
  return <ScreenContainer>{loading ? <View style={styles.center}><ActivityIndicator size="large" color="#0B776B" /></View> : <ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-forward" size={22} color="#0B776B" /></Pressable>{report ? <><View style={styles.hero}><View style={styles.icon}><MaterialIcons name="verified" size={25} color="#267A49" /></View><Text style={styles.title}>التقرير الطبي النهائي</Text><Text style={styles.subtitle}>محتوى ظاهر ضمن نطاق المريض والزيارة المكتملة فقط.</Text></View><View style={styles.card}><Text style={styles.cardTitle}>ملخص الزيارة</Text><Text style={styles.summary}>{report.summary}</Text><View style={styles.notice}><MaterialIcons name="shield" size={17} color="#267A49" /><Text style={styles.noticeText}>لا يُحفظ هذا التقرير في التخزين المحلي للتطبيق.</Text></View></View></> : <View style={styles.empty}><MaterialIcons name="lock-outline" size={32} color="#0B776B" /><Text style={styles.emptyTitle}>المحتوى غير متاح بعد</Text><Text style={styles.emptyText}>{error}</Text></View>}</ScrollView>}</ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20 }, center: { alignItems: "center", flex: 1, justifyContent: "center" }, back: { alignItems: "center", backgroundColor: "#EAF6F3", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, hero: { alignItems: "center", marginTop: 24 }, icon: { alignItems: "center", backgroundColor: "#E6F7ED", borderRadius: 18, height: 57, justifyContent: "center", width: 57 }, title: { color: "#183B36", fontSize: 22, fontWeight: "800", marginTop: 14, textAlign: "center" }, subtitle: { color: "#6A827C", fontSize: 12, lineHeight: 19, marginTop: 6, textAlign: "center" }, card: { backgroundColor: "#FFFFFF", borderColor: "#E0ECE8", borderRadius: 20, borderWidth: 1, marginTop: 24, padding: 17 }, cardTitle: { color: "#183B36", fontSize: 17, fontWeight: "800", textAlign: "right" }, summary: { color: "#31584F", fontSize: 14, lineHeight: 26, marginTop: 14, textAlign: "right" }, notice: { alignItems: "center", backgroundColor: "#EFF9F5", borderRadius: 12, flexDirection: "row-reverse", gap: 7, marginTop: 18, padding: 12 }, noticeText: { color: "#267A49", flex: 1, fontSize: 11, textAlign: "right" }, empty: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E0ECE8", borderRadius: 22, borderWidth: 1, marginTop: 50, padding: 28 }, emptyTitle: { color: "#183B36", fontSize: 18, fontWeight: "800", marginTop: 15 }, emptyText: { color: "#6A827C", fontSize: 13, lineHeight: 20, marginTop: 7, textAlign: "center" }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] } });
