import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useMediCare } from "@/lib/medicare-store";

export default function ProfileScreen() {
  const { visits, notifications, preferences, setAppointmentAlerts, setMedicalAlerts, resetLocalData } = useMediCare();
  const [privacyOpen, setPrivacyOpen] = useState(false);
  const [resetOpen, setResetOpen] = useState(false);

  return <ScreenContainer>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.profileHero}><View style={styles.profileMark}><MaterialIcons name="health-and-safety" size={31} color="#FFFFFF" /></View><Text style={styles.title}>MediCare Pro</Text><Text style={styles.subtitle}>مساحتك المحلية لمتابعة الزيارات المنزلية.</Text></View>
      <View style={styles.infoCard}><View style={styles.infoRow}><View style={styles.infoIcon}><MaterialIcons name="phonelink-lock" size={22} color="#0B776B" /></View><View style={styles.infoCopy}><Text style={styles.infoTitle}>وضع محلي آمن</Text><Text style={styles.infoText}>تُحفظ الزيارات والتنبيهات وإعداداتك على هذا الجهاز فقط. لا تتطلب المعاينة حساباً أو اتصالاً بخادم.</Text></View></View></View>
      <Text style={styles.sectionTitle}>إعدادات التنبيهات</Text>
      <View style={styles.settingCard}><View style={styles.settingRow}><Switch value={preferences.appointmentAlerts} onValueChange={setAppointmentAlerts} trackColor={{ false: "#D7E5E0", true: "#7CCBB8" }} thumbColor={preferences.appointmentAlerts ? "#0B776B" : "#F8FBFA"} /><View style={styles.settingCopy}><Text style={styles.infoTitle}>تنبيهات المواعيد</Text><Text style={styles.infoText}>يُنشئ التطبيق تنبيهاً عند حفظ زيارة جديدة.</Text></View></View><View style={styles.divider} /><View style={styles.settingRow}><Switch value={preferences.medicalAlerts} onValueChange={setMedicalAlerts} trackColor={{ false: "#D7E5E0", true: "#7CCBB8" }} thumbColor={preferences.medicalAlerts ? "#0B776B" : "#F8FBFA"} /><View style={styles.settingCopy}><Text style={styles.infoTitle}>التنبيهات المعلوماتية</Text><Text style={styles.infoText}>تتيح إضافة تذكيرات صحية داخل التطبيق.</Text></View></View></View>
      <Text style={styles.sectionTitle}>بيانات التطبيق</Text>
      <View style={styles.settingCard}><View style={styles.dataRow}><View style={styles.dataItem}><Text style={styles.dataValue}>{visits.length}</Text><Text style={styles.dataLabel}>زيارة</Text></View><View style={styles.dataDivider} /><View style={styles.dataItem}><Text style={styles.dataValue}>{notifications.length}</Text><Text style={styles.dataLabel}>تنبيه</Text></View></View><View style={styles.divider} /><Pressable onPress={() => setPrivacyOpen(true)} style={({ pressed }) => [styles.linkRow, pressed && styles.pressed]}><MaterialIcons name="chevron-left" size={22} color="#0B776B" /><Text style={styles.linkText}>معلومات الخصوصية</Text><MaterialIcons name="privacy-tip" size={20} color="#0B776B" /></Pressable><View style={styles.divider} /><Pressable onPress={() => setResetOpen(true)} style={({ pressed }) => [styles.linkRow, pressed && styles.pressed]}><MaterialIcons name="chevron-left" size={22} color="#B6403A" /><Text style={[styles.linkText, { color: "#B6403A" }]}>حذف البيانات المحلية</Text><MaterialIcons name="delete-outline" size={20} color="#B6403A" /></Pressable></View>
      <Text style={styles.version}>MediCare Pro Mobile · إصدار المعاينة</Text>
    </ScrollView>
    <Modal transparent visible={privacyOpen} animationType="fade" onRequestClose={() => setPrivacyOpen(false)}><View style={styles.modalOverlay}><View style={styles.modalCard}><View style={styles.modalIcon}><MaterialIcons name="privacy-tip" size={28} color="#0B776B" /></View><Text style={styles.modalTitle}>خصوصيتك أولاً</Text><Text style={styles.modalText}>هذه النسخة تحفظ معلومات الزيارات والتنبيهات وتفضيلاتك داخل مساحة تخزين محلية مرتبطة بالجهاز. يمكنك حذفها في أي وقت من هذه الشاشة.</Text><Pressable onPress={() => setPrivacyOpen(false)} style={({ pressed }) => [styles.modalButton, pressed && styles.pressed]}><Text style={styles.modalButtonText}>فهمت</Text></Pressable></View></View></Modal>
    <Modal transparent visible={resetOpen} animationType="fade" onRequestClose={() => setResetOpen(false)}><View style={styles.modalOverlay}><View style={styles.modalCard}><View style={[styles.modalIcon, { backgroundColor: "#FBEDEC" }]}><MaterialIcons name="delete-outline" size={28} color="#B6403A" /></View><Text style={styles.modalTitle}>حذف البيانات المحلية؟</Text><Text style={styles.modalText}>سيؤدي ذلك إلى إزالة الزيارات والتنبيهات وإعدادات هذا التطبيق من الجهاز. لا يمكن التراجع عن هذا الإجراء.</Text><View style={styles.modalActions}><Pressable onPress={() => setResetOpen(false)} style={({ pressed }) => [styles.cancelButton, pressed && styles.pressed]}><Text style={styles.cancelText}>إلغاء</Text></Pressable><Pressable onPress={() => { resetLocalData(); setResetOpen(false); }} style={({ pressed }) => [styles.deleteButton, pressed && styles.pressed]}><Text style={styles.deleteText}>حذف البيانات</Text></Pressable></View></View></View></Modal>
  </ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 35 }, profileHero: { alignItems: "center", marginBottom: 21 }, profileMark: { alignItems: "center", backgroundColor: "#0B776B", borderRadius: 24, height: 72, justifyContent: "center", width: 72 }, title: { color: "#183B36", fontSize: 25, fontWeight: "800", marginTop: 13 }, subtitle: { color: "#6A827C", fontSize: 13, marginTop: 5, textAlign: "center" },
  infoCard: { backgroundColor: "#FFFFFF", borderColor: "#E0ECE8", borderRadius: 19, borderWidth: 1, padding: 15 }, infoRow: { alignItems: "flex-start", flexDirection: "row-reverse" }, infoIcon: { alignItems: "center", backgroundColor: "#E6F5F2", borderRadius: 13, height: 43, justifyContent: "center", width: 43 }, infoCopy: { flex: 1, marginRight: 11 }, infoTitle: { color: "#183B36", fontSize: 14, fontWeight: "800", textAlign: "right" }, infoText: { color: "#6A827C", fontSize: 12, lineHeight: 18, marginTop: 4, textAlign: "right" },
  sectionTitle: { color: "#183B36", fontSize: 17, fontWeight: "800", marginBottom: 11, marginTop: 24, textAlign: "right" }, settingCard: { backgroundColor: "#FFFFFF", borderColor: "#E0ECE8", borderRadius: 19, borderWidth: 1, padding: 15 }, settingRow: { alignItems: "center", flexDirection: "row-reverse", gap: 13 }, settingCopy: { flex: 1 }, divider: { backgroundColor: "#E8F0ED", height: 1, marginVertical: 14 },
  dataRow: { flexDirection: "row-reverse", justifyContent: "space-around" }, dataItem: { alignItems: "center", flex: 1 }, dataValue: { color: "#0B776B", fontSize: 24, fontWeight: "800" }, dataLabel: { color: "#6A827C", fontSize: 12, marginTop: 3 }, dataDivider: { backgroundColor: "#E8F0ED", width: 1 }, linkRow: { alignItems: "center", flexDirection: "row-reverse" }, linkText: { color: "#0B776B", flex: 1, fontSize: 14, fontWeight: "700", marginHorizontal: 9, textAlign: "right" }, version: { color: "#91A49F", fontSize: 11, marginTop: 22, textAlign: "center" },
  modalOverlay: { alignItems: "center", backgroundColor: "rgba(17, 49, 43, 0.35)", flex: 1, justifyContent: "center", padding: 24 }, modalCard: { backgroundColor: "#FFFFFF", borderRadius: 23, maxWidth: 380, padding: 22, width: "100%" }, modalIcon: { alignItems: "center", alignSelf: "center", backgroundColor: "#E6F5F2", borderRadius: 18, height: 56, justifyContent: "center", width: 56 }, modalTitle: { color: "#183B36", fontSize: 19, fontWeight: "800", marginTop: 15, textAlign: "center" }, modalText: { color: "#58766F", fontSize: 13, lineHeight: 21, marginTop: 9, textAlign: "center" }, modalButton: { alignItems: "center", backgroundColor: "#0B776B", borderRadius: 13, marginTop: 20, paddingVertical: 12 }, modalButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, modalActions: { flexDirection: "row-reverse", gap: 9, marginTop: 21 }, cancelButton: { alignItems: "center", backgroundColor: "#F2F6F4", borderRadius: 13, flex: 1, paddingVertical: 12 }, cancelText: { color: "#41665D", fontSize: 14, fontWeight: "800" }, deleteButton: { alignItems: "center", backgroundColor: "#B6403A", borderRadius: 13, flex: 1, paddingVertical: 12 }, deleteText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" },
  pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
});
