import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { getRemoteInvoice, recordRemoteDemoPayment, renewPatientSession, type PatientInvoice } from "@/lib/patient-api";
import { useMediCare } from "@/lib/medicare-store";

export default function InvoiceDetailScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { session } = useMediCare(); const [invoice, setInvoice] = useState<PatientInvoice | null>(null); const [loading, setLoading] = useState(true); const [paying, setPaying] = useState(false); const [error, setError] = useState(""); const visitId = Number(id);
  const load = useCallback(async () => { if (!session || !Number.isInteger(visitId)) { setError("سجّل الدخول لعرض الفاتورة المرتبطة بالزيارة."); setLoading(false); return; } try { setInvoice(await getRemoteInvoice(await renewPatientSession(session), visitId)); } catch (reason) { setError(reason instanceof Error ? reason.message : "الفاتورة غير متاحة لهذه الزيارة."); } finally { setLoading(false); } }, [session, visitId]);
  useEffect(() => { void load(); }, [load]);
  const pay = async () => { if (!session) return; setPaying(true); try { setInvoice(await recordRemoteDemoPayment(await renewPatientSession(session), visitId)); Alert.alert("تم التسجيل", "تم تسجيل السداد التجريبي وتحديث حالة الفاتورة."); } catch (reason) { Alert.alert("تعذر تسجيل السداد", reason instanceof Error ? reason.message : "حاول مرة أخرى."); } finally { setPaying(false); } };
  return <ScreenContainer>{loading ? <View style={styles.center}><ActivityIndicator size="large" color="#0B776B" /></View> : <ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-forward" size={22} color="#0B776B" /></Pressable>{invoice ? <View style={styles.card}><View style={styles.top}><View><Text style={styles.title}>فاتورة الزيارة</Text><Text style={styles.number}>{invoice.invoiceNo}</Text></View><View style={[styles.badge, { backgroundColor: invoice.status === "PAID" ? "#E6F7ED" : "#FFF3DB" }]}><Text style={[styles.badgeText, { color: invoice.status === "PAID" ? "#267A49" : "#9A5B12" }]}>{invoice.status === "PAID" ? "مدفوعة" : "بانتظار السداد التجريبي"}</Text></View></View><View style={styles.total}><Text style={styles.totalLabel}>إجمالي الزيارة</Text><Text style={styles.totalValue}>{(invoice.totalHalalas / 100).toLocaleString("ar-SA")} ر.س</Text></View><Text style={styles.caption}>هذه النسخة لا تجمع بيانات دفع أو تنقل أموالاً فعلية.</Text>{invoice.status === "DUE" ? <Pressable disabled={paying} onPress={() => void pay()} style={({ pressed }) => [styles.primary, paying && styles.disabled, pressed && styles.pressed]}><Text style={styles.primaryText}>{paying ? "جارٍ التسجيل…" : "تسجيل سداد تجريبي"}</Text></Pressable> : null}</View> : <View style={styles.empty}><MaterialIcons name="lock-outline" size={32} color="#0B776B" /><Text style={styles.emptyTitle}>الفاتورة غير متاحة بعد</Text><Text style={styles.emptyText}>{error}</Text></View>}</ScrollView>}</ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20 }, center: { alignItems: "center", flex: 1, justifyContent: "center" }, back: { alignItems: "center", backgroundColor: "#EAF6F3", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, card: { backgroundColor: "#FFFFFF", borderColor: "#E0ECE8", borderRadius: 20, borderWidth: 1, marginTop: 24, padding: 18 }, top: { alignItems: "flex-start", flexDirection: "row-reverse", justifyContent: "space-between" }, title: { color: "#183B36", fontSize: 20, fontWeight: "800", textAlign: "right" }, number: { color: "#6A827C", fontSize: 12, marginTop: 5, textAlign: "right" }, badge: { borderRadius: 99, paddingHorizontal: 10, paddingVertical: 7 }, badgeText: { fontSize: 11, fontWeight: "800" }, total: { alignItems: "center", backgroundColor: "#F7FAF9", borderRadius: 14, flexDirection: "row-reverse", justifyContent: "space-between", marginTop: 24, padding: 15 }, totalLabel: { color: "#6A827C", fontSize: 13 }, totalValue: { color: "#183B36", fontSize: 20, fontWeight: "800" }, caption: { color: "#6A827C", fontSize: 11, lineHeight: 18, marginTop: 16, textAlign: "right" }, primary: { alignItems: "center", backgroundColor: "#0B776B", borderRadius: 13, marginTop: 20, minHeight: 49, justifyContent: "center" }, primaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, empty: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E0ECE8", borderRadius: 22, borderWidth: 1, marginTop: 50, padding: 28 }, emptyTitle: { color: "#183B36", fontSize: 18, fontWeight: "800", marginTop: 15 }, emptyText: { color: "#6A827C", fontSize: 13, lineHeight: 20, marginTop: 7, textAlign: "center" }, disabled: { opacity: 0.55 }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] } });
